import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import { api, Citation } from '../api'

type Props = { citation: Citation | null; onClose: () => void }

export function VerseDrawer({ citation, onClose }: Props) {
  const [text, setText] = useState<string | null>(null)
  const [translation, setTranslation] = useState<string>('WEB')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!citation) return
    setText(null)
    setError(null)
    setLoading(true)
    api
      .lookupVerse(citation.book, citation.chapter, citation.verse_start, citation.verse_end, translation)
      .then((res) => {
        setText(res.text)
        setTranslation(res.translation)
      })
      .catch((e) => setError(e.message || 'Verse not found'))
      .finally(() => setLoading(false))
  }, [citation, translation])

  if (!citation) return null

  const refLabel =
    citation.verse_start === citation.verse_end
      ? `${citation.book} ${citation.chapter}:${citation.verse_start}`
      : `${citation.book} ${citation.chapter}:${citation.verse_start}-${citation.verse_end}`

  return (
    <div className="fixed inset-0 z-40 flex">
      <div className="flex-1 bg-ink-900/30" onClick={onClose} />
      <aside className="w-full max-w-md bg-white shadow-xl border-l border-ink-100 p-6 overflow-y-auto">
        <div className="flex items-center justify-between mb-2">
          <span className="text-xs uppercase tracking-wide text-ink-400">Canonical verse</span>
          <button className="btn-ghost" onClick={onClose}><X className="h-4 w-4" /></button>
        </div>
        <h2 className="text-2xl text-ink-800 mb-3">{refLabel}</h2>
        <div className="mb-3">
          <label className="label">Translation</label>
          <select className="input" value={translation} onChange={(e) => setTranslation(e.target.value)}>
            <option value="WEB">WEB (World English Bible)</option>
            <option value="KJV">KJV (King James Version)</option>
          </select>
        </div>
        {loading && <p className="text-sm text-ink-400">Looking up...</p>}
        {error && (
          <div className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">
            {error} - this citation could not be verified against the canonical Bible.
          </div>
        )}
        {text && (
          <blockquote className="font-serif text-lg leading-relaxed text-ink-800 border-l-4 border-gold-300 pl-4 italic">
            {text}
          </blockquote>
        )}
        <p className="mt-6 text-xs text-ink-400">
          Verified directly against the canonical Bible store - not regenerated by the model.
        </p>
      </aside>
    </div>
  )
}
